module Seeds
  def self.seed_companies
    [
      { name: '0verflow', founded_on: Date.new(1997) },
      { name: '1C Company', founded_on: Date.new(1991) },
      { name: '1st Playable Productions', founded_on: Date.new(2005) },
      { name: '2K Czech', founded_on: Date.new(1997) },
      { name: '2K Games', founded_on: Date.new(2005) },
      { name: '2XL Games', founded_on: Date.new(2006) },
      { name: '343 Industries', founded_on: Date.new(2009) },
      { name: '38 Studios', founded_on: Date.new(2006) },
      { name: '3D Realms', founded_on: Date.new(1987) },
      { name: '3G Studios', founded_on: Date.new(2002) },
      { name: '42 Entertainment', founded_on: Date.new(1993) },
      { name: '4A Games', founded_on: Date.new(2005) },
      { name: '505 Games', founded_on: Date.new(2006) },
      { name: '5pb. Inc.', founded_on: Date.new(2005) },
      { name: '5th Cell', founded_on: Date.new(2003) },
      { name: '989 Studios', founded_on: Date.new(1995) },
      { name: 'Access Games', founded_on: Date.new(2002) },
      { name: 'Access Software', founded_on: Date.new(1982) },
      { name: 'Acclaim Entertainment', founded_on: Date.new(1987) },
      { name: 'Accolade', founded_on: Date.new(1984) },
      { name: 'ACE Team', founded_on: Date.new(2007) },
      { name: 'Acheron Design', founded_on: Date.new(2004) },
      { name: 'Action Forms', founded_on: Date.new(1995) },
      { name: 'Active Gaming Media', founded_on: Date.new(2006) },
      { name: 'Active Gaming Media AGM', founded_on: Date.new(2006) },
      { name: 'Activision', founded_on: Date.new(1979) },
      { name: 'Activision Blizzard', founded_on: Date.new(2008) },
      { name: 'Adventure Soft', founded_on: Date.new(1992) },
      { name: 'Agetec', founded_on: Date.new(1998) },
      { name: 'Akella', founded_on: Date.new(1995) },
      { name: 'Aki Corporation', founded_on: Date.new(1995) },
      { name: 'Alfa System', founded_on: Date.new(1988) },
      { name: 'Alten8', founded_on: Date.new(2005) },
      { name: 'Amazon Game Studios', founded_on: Date.new(2012) },
      { name: 'Ancient', founded_on: Date.new(1990) },
      { name: 'Anino Games', founded_on: Date.new(2001) },
      { name: 'Ankama Games', founded_on: Date.new(2001) },
      { name: 'Anuman', founded_on: Date.new(2000) },
      { name: 'Apogee Software', founded_on: Date.new(2008) },
      { name: 'AQ Interactive', founded_on: Date.new(2000) },
      { name: 'Arc System Works', founded_on: Date.new(1988) },
      { name: 'ArenaNet', founded_on: Date.new(2000) },
      { name: 'Arika', founded_on: Date.new(1995) },
      { name: 'Arkane Studios', founded_on: Date.new(1999) },
      { name: 'Arkedo Studio', founded_on: Date.new(2006) },
      { name: 'Art Co., Ltd', founded_on: Date.new(1995) },
      { name: 'Artdink', founded_on: Date.new(1986) },
      { name: 'ArtePiazza', founded_on: Date.new(1989) },
      { name: 'Artificial Studios', founded_on: Date.new(2001) },
      { name: 'Artoon', founded_on: Date.new(1999) },
      { name: 'Ascaron', founded_on: Date.new(1989) },
      { name: 'Asmik Corporation of America', founded_on: Date.new(1985) },
      { name: 'Asobo Studio', founded_on: Date.new(2002) },
      { name: 'Aspyr Media', founded_on: Date.new(1996) },
      { name: 'Atari', founded_on: Date.new(1972,6,27) },
      { name: 'Atlus', founded_on: Date.new(1986) },
      { name: 'Atomic Planet Entertainment', founded_on: Date.new(2000) },
      { name: 'Attic Entertainment Software', founded_on: Date.new(1990) },
      { name: 'Autumn Games', founded_on: Date.new(2007) },
      { name: 'Avalanche Software', founded_on: Date.new(1995) },
      { name: 'Avalanche Studios', founded_on: Date.new(2003) },
      { name: 'Aventurine SA', founded_on: Date.new(2002) },
      { name: 'Babaroga', founded_on: Date.new(2001) },
      { name: 'Backbone Entertainment', founded_on: Date.new(1992) },
      { name: 'Bandai Games', founded_on: Date.new(1950) },
      { name: 'Bandai Namco', founded_on: Date.new(2006) },
      { name: 'Bandai Namco Studios', founded_on: Date.new(2012) },
      { name: 'Banpresto', founded_on: Date.new(1977) },
      { name: 'Bauhaus Entertainment', founded_on: Date.new(2006) },
      { name: 'Beenox', founded_on: Date.new(2000) },
      { name: 'Behaviour Interactive', founded_on: Date.new(1992) },
      { name: 'Behemoth, The', founded_on: Date.new(2002) },
      { name: 'Bethesda Softworks', founded_on: Date.new(1985) },
      { name: 'Big Fish Games', founded_on: Date.new(2002) },
      { name: 'Big Huge Games', founded_on: Date.new(2000) },
      { name: 'Bigben Interactive', founded_on: Date.new(1981) },
      { name: 'Binary Hammer', founded_on: Date.new(2008) },
      { name: 'BioWare', founded_on: Date.new(1995) },
      { name: 'Bits Studios', founded_on: Date.new(1991) },
      { name: 'Bizarre Creations', founded_on: Date.new(1994) },
      { name: 'Black Forest Games', founded_on: Date.new(2012) },
      { name: 'Black Rock Studio', founded_on: Date.new(1998) },
      { name: 'Black Shell Games', founded_on: Date.new(2012) },
      { name: 'Black Wing Foundation', founded_on: Date.new(2006) },
      { name: 'Blitz Games Studios', founded_on: Date.new(1990) },
      { name: 'Blizzard Entertainment', founded_on: Date.new(1991) },
      { name: 'Blue Byte Software', founded_on: Date.new(1988) },
      { name: 'Blue Fang Games', founded_on: Date.new(1998) },
      { name: 'Blue Tongue Entertainment', founded_on: Date.new(1995) },
      { name: 'Bohemia Interactive', founded_on: Date.new(1999) },
      { name: 'Boss Fight Entertainment', founded_on: Date.new(2013) },
      { name: 'Boss Key Productions', founded_on: Date.new(2014) },
      { name: 'BreakAway Games', founded_on: Date.new(1998) },
      { name: 'Brøderbund', founded_on: Date.new(1980) },
      { name: 'Brownie Brown', founded_on: Date.new(2000) },
      { name: 'Bug-Byte', founded_on: Date.new(1980) },
      { name: 'Bugbear Entertainment', founded_on: Date.new(2000) },
      { name: 'Buka Entertainment', founded_on: Date.new(1993) },
      { name: 'Bullet-Proof Software', founded_on: Date.new(1980) },
      { name: 'Bullfrog Productions', founded_on: Date.new(1987) },
      { name: 'Bungie', founded_on: Date.new(1997) },
      { name: 'Bungie Studios', founded_on: Date.new(1991) },
      { name: 'Camerica', founded_on: Date.new(1988) },
      { name: 'Capcom', founded_on: Date.new(1979) },
      { name: 'Capcom Vancouver', founded_on: Date.new(2005) },
      { name: 'Cauldron', founded_on: Date.new(1996) },
      { name: 'Cave', founded_on: Date.new(1994) },
      { name: 'Cavia', founded_on: Date.new(2000) },
      { name: 'CCP Games', founded_on: Date.new(1997) },
      { name: 'CD Projekt RED', founded_on: Date.new(1994) },
      { name: 'cdv Software Entertainment', founded_on: Date.new(1989) },
      { name: 'Centuri', founded_on: Date.new(1974) },
      { name: 'Certain Affinity', founded_on: Date.new(2006) },
      { name: 'Chunsoft', founded_on: Date.new(1984) },
      { name: 'CI Games', founded_on: Date.new(2002) },
      { name: 'Cing', founded_on: Date.new(1999) },
      { name: 'Clap Hanz', founded_on: Date.new(1998) },
      { name: 'Climax Entertainment', founded_on: Date.new(1990) },
      { name: 'Climax Studios', founded_on: Date.new(1988) },
      { name: 'Cloud Imperium Games', founded_on: Date.new(2012) },
      { name: 'Coded Illusions', founded_on: Date.new(2005) },
      { name: 'Codemasters', founded_on: Date.new(1985) },
      { name: 'Coktel Vision', founded_on: Date.new(1985) },
      { name: 'Coleco', founded_on: Date.new(1932) },
      { name: 'Color Dreams', founded_on: Date.new(1988) },
      { name: 'Colossal Order', founded_on: Date.new(2009) },
      { name: 'Compile Heart', founded_on: Date.new(2006) },
      { name: 'Conspiracy Entertainment', founded_on: Date.new(1997) },
      { name: 'Core Design', founded_on: Date.new(1988) },
      { name: 'Crafts & Meister', founded_on: Date.new(2004) },
      { name: 'Crave Entertainment', founded_on: Date.new(1997) },
      { name: 'Creat Studios', founded_on: Date.new(1990) },
      { name: 'Creative Assembly', founded_on: Date.new(1987) },
      { name: 'Criterion Games', founded_on: Date.new(1993) },
      { name: 'Croteam', founded_on: Date.new(1993) },
      { name: 'Cryo Interactive', founded_on: Date.new(1992) },
      { name: 'Cryptic Studios', founded_on: Date.new(2000) },
      { name: 'Crystal Dynamics', founded_on: Date.new(1992) },
      { name: 'Crytek', founded_on: Date.new(1999) },
      { name: 'Culture Brain', founded_on: Date.new(1980) },
      { name: 'Cyan Worlds', founded_on: Date.new(1987) },
      { name: 'Cyanide', founded_on: Date.new(2000) },
      { name: 'CyberConnect2', founded_on: Date.new(1996) },
      { name: 'Cyberdreams', founded_on: Date.new(2007) },
      { name: 'Cyberlore Studios', founded_on: Date.new(1992) },
      { name: 'D3 Publisher', founded_on: Date.new(1996) },
      { name: 'Data East', founded_on: Date.new(1976) },
      { name: 'Day 1 Studios', founded_on: Date.new(2001) },
      { name: 'Daybreak Game Company', founded_on: Date.new(1995) },
      { name: 'Deadline Games', founded_on: Date.new(1996) },
      { name: 'Deck13', founded_on: Date.new(2001) },
      { name: 'Deep Silver', founded_on: Date.new(1994) },
      { name: 'Demiurge Studios', founded_on: Date.new(2002) },
      { name: 'Destineer', founded_on: Date.new(2000) },
      { name: 'Dhruva Interactive', founded_on: Date.new(1997) },
      { name: 'Die Gute Fabrik', founded_on: Date.new(2006) },
      { name: 'Digital Illusions CE', founded_on: Date.new(1988) },
      { name: 'Digital Reality', founded_on: Date.new(1991) },
      { name: 'Dimps', founded_on: Date.new(2000) },
      { name: 'Disney Interactive Studios', founded_on: Date.new(1988) },
      { name: 'Double Fine Productions', founded_on: Date.new(2000) },
      { name: 'Double Helix Games', founded_on: Date.new(2007) },
      { name: 'DreamCatcher Games', founded_on: Date.new(1996) },
      { name: 'Dtp entertainment', founded_on: Date.new(1995) },
      { name: 'Egosoft', founded_on: Date.new(1988) },
      { name: 'Eidos Interactive', founded_on: Date.new(1990) },
      { name: 'Electronic Arts', founded_on: Date.new(1982) },
      { name: 'Electronic Arts/EA Games', founded_on: Date.new(1982) },
      { name: 'Elev8 Games', founded_on: Date.new(2013) },
      { name: 'Engine Software', founded_on: Date.new(1995) },
      { name: 'Enix', founded_on: Date.new(1975) },
      { name: 'Ensemble Studios', founded_on: Date.new(1995) },
      { name: 'Epic Games', founded_on: Date.new(1991) },
      { name: 'Epic Games Poland', founded_on: Date.new(2002) },
      { name: 'Epicenter Studios', founded_on: Date.new(2007) },
      { name: 'Epyx', founded_on: Date.new(1978) },
      { name: 'Etranges Libellules', founded_on: Date.new(1994) },
      { name: 'Eugen Systems', founded_on: Date.new(2000) },
      { name: 'Eurocom', founded_on: Date.new(1988) },
      { name: 'Evolution Studios', founded_on: Date.new(1999) },
      { name: 'F4', founded_on: Date.new(2002) },
      { name: 'Facepunch Studios', founded_on: Date.new(2009) },
      { name: 'FarSight Studios', founded_on: Date.new(1989) },
      { name: 'FASA', founded_on: Date.new(1980) },
      { name: 'Fatshark', founded_on: Date.new(2008) },
      { name: 'feelplus', founded_on: Date.new(1992) },
      { name: 'Feral Interactive', founded_on: Date.new(1999) },
      { name: 'Firaxis Games', founded_on: Date.new(1996) },
      { name: 'Firefly Studios', founded_on: Date.new(1999) },
      { name: 'First Star Software', founded_on: Date.new(1982) },
      { name: 'Flagship Studios', founded_on: Date.new(2003) },
      { name: 'Flying Wild Hog', founded_on: Date.new(2009) },
      { name: 'Foundation 9 Entertainment', founded_on: Date.new(1992) },
      { name: 'Fox Interactive', founded_on: Date.new(1982) },
      { name: 'Fresh Games', founded_on: Date.new(2002) },
      { name: 'Frictional Games', founded_on: Date.new(2001) },
      { name: 'Frogwares', founded_on: Date.new(2000) },
      { name: 'FromSoftware', founded_on: Date.new(1986) },
      { name: 'Frontier Developments', founded_on: Date.new(1994) },
      { name: 'Frozenbyte', founded_on: Date.new(2001) },
      { name: 'Fujisankei Communications International', founded_on: Date.new(1986) },
      { name: 'FUN Labs', founded_on: Date.new(1999) },
      { name: 'Funcom', founded_on: Date.new(1993) },
      { name: 'Futuremark', founded_on: Date.new(1997) },
      { name: 'Gaijin Entertainment', founded_on: Date.new(2002) },
      { name: 'Game Arts', founded_on: Date.new(1985) },
      { name: 'Game Freak', founded_on: Date.new(1989) },
      { name: 'Game Stream Ltd', founded_on: Date.new(2005) },
      { name: 'Gamecock', founded_on: Date.new(2007) },
      { name: 'GameHouse', founded_on: Date.new(1998) },
      { name: 'Gameloft', founded_on: Date.new(1999) },
      { name: 'GAMÉRICA', founded_on: Date.new(2011) },
      { name: 'Games2win', founded_on: Date.new(2005) },
      { name: 'Gearbox Software', founded_on: Date.new(1999) },
      { name: 'Geewa', founded_on: Date.new(2005) },
      { name: 'Genki', founded_on: Date.new(1990) },
      { name: 'Ghostlight', founded_on: Date.new(2004) },
      { name: 'Giant Interactive', founded_on: Date.new(2001) },
      { name: 'Global Star Software', founded_on: Date.new(1992) },
      { name: 'GOD Games', founded_on: Date.new(1988) },
      { name: 'GOG Ltd', founded_on: Date.new(2008) },
      { name: 'Gogii Games', founded_on: Date.new(2006) },
      { name: 'Good-Feel', founded_on: Date.new(2005) },
      { name: 'Grasshopper Manufacture', founded_on: Date.new(1998) },
      { name: 'Gravity', founded_on: Date.new(2000) },
      { name: 'Gremlin Interactive', founded_on: Date.new(1984) },
      { name: 'Grezzo', founded_on: Date.new(2006) },
      { name: 'Griptonite Games', founded_on: Date.new(1994) },
      { name: 'GSC Game World', founded_on: Date.new(1995) },
      { name: 'GSC World Publishing', founded_on: Date.new(2004) },
      { name: 'GT Interactive', founded_on: Date.new(1993) },
      { name: 'Guerrilla Games', founded_on: Date.new(2000) },
      { name: 'GungHo Online Entertainment', founded_on: Date.new(1998) },
      { name: 'Gust Corporation', founded_on: Date.new(1993) },
      { name: 'Haemimont Games', founded_on: Date.new(1997) },
      { name: 'HAL Laboratory', founded_on: Date.new(1980) },
      { name: 'Halfbrick', founded_on: Date.new(2001) },
      { name: 'Hanaho', founded_on: Date.new(1992) },
      { name: 'Harebrained Schemes', founded_on: Date.new(2011) },
      { name: 'Harmonix Music Systems', founded_on: Date.new(1995) },
      { name: 'Hasbro Interactive', founded_on: Date.new(1995) },
      { name: 'HB Studios', founded_on: Date.new(2000) },
      { name: 'Her Interactive', founded_on: Date.new(1995) },
      { name: 'HeroCraft', founded_on: Date.new(2001) },
      { name: 'Hi Tech Expressions', founded_on: Date.new(1988) },
      { name: 'High Moon Studios', founded_on: Date.new(2005) },
      { name: 'High Voltage Software', founded_on: Date.new(1993) },
      { name: 'Hoplon Infotainment', founded_on: Date.new(2004) },
      { name: 'Hothead Games', founded_on: Date.new(2006) },
      { name: 'Housemarque', founded_on: Date.new(1995) },
      { name: 'Hudson Soft', founded_on: Date.new(1973) },
      { name: 'Human Head Studios', founded_on: Date.new(1997) },
      { name: 'Humongous Entertainment', founded_on: Date.new(1992) },
      { name: 'Hyperion Entertainment', founded_on: Date.new(1999) },
      { name: 'Iceberg Interactive', founded_on: Date.new(2009) },
      { name: 'id Software', founded_on: Date.new(1991) },
      { name: 'Idea Factory', founded_on: Date.new(1994) },
      { name: 'Ignition Entertainment', founded_on: Date.new(2002) },
      { name: 'Imageepoch', founded_on: Date.new(2005) },
      { name: 'Imagic', founded_on: Date.new(1981) },
      { name: 'Incredible Technologies', founded_on: Date.new(1985) },
      { name: 'indiePub Entertainment', founded_on: Date.new(2008) },
      { name: 'indieszero', founded_on: Date.new(1997) },
      { name: 'Infinity Ward', founded_on: Date.new(2002) },
      { name: 'Infocom', founded_on: Date.new(1979) },
      { name: 'Infogrames', founded_on: Date.new(1983) },
      { name: 'Innerloop Studios', founded_on: Date.new(1996) },
      { name: 'Inscape', founded_on: Date.new(1994) },
      { name: 'Insomniac Games', founded_on: Date.new(1994) },
      { name: 'Intelligent Systems', founded_on: Date.new(1986) },
      { name: 'Interceptor Entertainment', founded_on: Date.new(2010) },
      { name: 'Interceptor Micros', founded_on: Date.new(1980) },
      { name: 'Interplay Entertainment', founded_on: Date.new(1983) },
      { name: 'Introversion Software', founded_on: Date.new(2002) },
      { name: 'inXile Entertainment', founded_on: Date.new(2002) },
      { name: 'IO Interactive', founded_on: Date.new(1998) },
      { name: 'Ion Storm', founded_on: Date.new(1996) },
      { name: 'Irem', founded_on: Date.new(1974) },
      { name: 'Iron Galaxy Studios', founded_on: Date.new(2008) },
      { name: 'Irrational Games', founded_on: Date.new(1996) },
      { name: 'Jadestone Group', founded_on: Date.new(2000) },
      { name: 'Jagex', founded_on: Date.new(2001) },
      { name: 'Jaleco', founded_on: Date.new(1974) },
      { name: 'Javaground', founded_on: Date.new(2001) },
      { name: 'JoWood Entertainment AG', founded_on: Date.new(1995) },
      { name: 'JoWooD Productions', founded_on: Date.new(1995) },
      { name: 'Juice Games', founded_on: Date.new(2003) },
      { name: 'Jupiter', founded_on: Date.new(1996) },
      { name: 'JV Games', founded_on: Date.new(1999) },
      { name: 'K2 Network (Gamersfirst)', founded_on: Date.new(2001) },
      { name: 'Kairosoft', founded_on: Date.new(1996) },
      { name: 'Kalypso Media', founded_on: Date.new(2006) },
      { name: 'Kaneko', founded_on: Date.new(1980) },
      { name: 'Kaos Studios', founded_on: Date.new(2006) },
      { name: 'Kemco', founded_on: Date.new(1984) },
      { name: 'Kiloo Games', founded_on: Date.new(2000) },
      { name: 'Klei Entertainment', founded_on: Date.new(2005) },
      { name: 'Koch Media', founded_on: Date.new(1994) },
      { name: 'Koei', founded_on: Date.new(1976) },
      { name: 'Koei Tecmo', founded_on: Date.new(2009) },
      { name: 'Konami', founded_on: Date.new(1969) },
      { name: 'Kongzhong', founded_on: Date.new(2002) },
      { name: 'Krome Studios', founded_on: Date.new(1999) },
      { name: 'Krome Studios Melbourne', founded_on: Date.new(1988) },
      { name: 'Kuju Entertainment', founded_on: Date.new(1998) },
      { name: 'Kuma Reality Games', founded_on: Date.new(2003) },
      { name: 'Kush Games', founded_on: Date.new(1998) },
      { name: 'Larian Studios', founded_on: Date.new(1996) },
      { name: 'Legacy Interactive', founded_on: Date.new(1998) },
      { name: 'Legendo Entertainment', founded_on: Date.new(2004) },
      { name: 'LEGO Group', founded_on: Date.new(1932) },
      { name: 'Level-5', founded_on: Date.new(1998) },
      { name: 'Linden Lab', founded_on: Date.new(1999) },
      { name: 'Linux Game Publishing', founded_on: Date.new(2001) },
      { name: 'Lionhead Studios', founded_on: Date.new(1997) },
      { name: 'Liquid Entertainment', founded_on: Date.new(1999) },
      { name: 'Little Green Men Games', founded_on: Date.new(2006) },
      { name: 'LJN', founded_on: Date.new(1970) },
      { name: 'LK Avalon', founded_on: Date.new(1989) },
      { name: 'Llamasoft', founded_on: Date.new(1982) },
      { name: 'Loki Software', founded_on: Date.new(1998) },
      { name: 'Looking Glass Studios', founded_on: Date.new(1990) },
      { name: 'LucasArts', founded_on: Date.new(1982) },
      { name: 'Luma Arcade', founded_on: Date.new(2006) },
      { name: 'Luxoflux', founded_on: Date.new(1998) },
      { name: 'M-Inverse', founded_on: Date.new(2005) },
      { name: 'MachineGames', founded_on: Date.new(2009) },
      { name: 'Magenta Software', founded_on: Date.new(1994) },
      { name: 'Majesco Entertainment', founded_on: Date.new(1986) },
      { name: 'Marvelous AQL', founded_on: Date.new(2000) },
      { name: 'Marvelous Entertainment', founded_on: Date.new(1997) },
      { name: 'Massive Entertainment', founded_on: Date.new(1997) },
      { name: 'Masthead Studios', founded_on: Date.new(2005) },
      { name: 'Mastiff', founded_on: Date.new(2002) },
      { name: 'Matrix Games', founded_on: Date.new(2000) },
      { name: 'Mattel Interactive', founded_on: Date.new(1986) },
      { name: 'Maximum Games', founded_on: Date.new(2009) },
      { name: 'Maxis', founded_on: Date.new(1987) },
      { name: 'Maxis Software', founded_on: Date.new(1987) },
      { name: 'Mean Hamster Software', founded_on: Date.new(1985) },
      { name: 'Media Molecule', founded_on: Date.new(2006) },
      { name: 'Mediatonic', founded_on: Date.new(2005) },
      { name: 'MegaZebra', founded_on: Date.new(2009) },
      { name: 'Meldac', founded_on: Date.new(1990) },
      { name: 'Mercury Steam', founded_on: Date.new(2002) },
      { name: 'Metropolis Software', founded_on: Date.new(1992) },
      { name: 'Microïds', founded_on: Date.new(1984) },
      { name: 'MicroProse', founded_on: Date.new(1982) },
      { name: 'Microsoft Corporation', founded_on: Date.new(1975,4,4) },
      { name: 'Microsoft Game Studios', founded_on: Date.new(2002) },
      { name: 'Microsoft Studios', founded_on: Date.new(2002) },
      { name: 'Midway Games', founded_on: Date.new(1988) },
      { name: 'Milestone', founded_on: Date.new(2003) },
      { name: 'Milestone S.r.l.', founded_on: Date.new(1996) },
      { name: 'Mind Candy', founded_on: Date.new(2004) },
      { name: 'Mindscape', founded_on: Date.new(1980) },
      { name: 'Mistwalker', founded_on: Date.new(2004) },
      { name: 'Mitchell Corporation', founded_on: Date.new(1960) },
      { name: 'Modoka Studios', founded_on: Date.new(2012) },
      { name: 'Mojang AB', founded_on: Date.new(2009) },
      { name: 'Monolith Productions', founded_on: Date.new(1994) },
      { name: 'Monolith Soft', founded_on: Date.new(1999) },
      { name: 'Muse Software', founded_on: Date.new(1978) },
      { name: 'Mythic Entertainment', founded_on: Date.new(1996) },
      { name: 'n-Space', founded_on: Date.new(1994) },
      { name: 'Nadeo', founded_on: Date.new(2000) },
      { name: 'Namco', founded_on: Date.new(1955) },
      { name: 'Nanobit', founded_on: Date.new(2008) },
      { name: 'Natsume', founded_on: Date.new(1987) },
      { name: 'Naughty Dog', founded_on: Date.new(1986) },
      { name: 'NCsoft', founded_on: Date.new(1997) },
      { name: 'NDOORS Corporation', founded_on: Date.new(1999) },
      { name: 'NEC', founded_on: Date.new(1899,7,17) },
      { name: 'Neowiz', founded_on: Date.new(1997) },
      { name: 'Nerve Software', founded_on: Date.new(1999) },
      { name: 'NetDevil', founded_on: Date.new(1997) },
      { name: 'Netdragon', founded_on: Date.new(1997) },
      { name: 'Netease', founded_on: Date.new(1997) },
      { name: 'NetherRealm Studios', founded_on: Date.new(2010) },
      { name: 'Neversoft', founded_on: Date.new(1994) },
      { name: 'New World Computing', founded_on: Date.new(1984) },
      { name: 'Nexon', founded_on: Date.new(1994) },
      { name: 'Next Level Games', founded_on: Date.new(2002) },
      { name: 'NGD Studios', founded_on: Date.new(2002) },
      { name: 'Nibris', founded_on: Date.new(2000) },
      { name: 'Nihon Bussan', founded_on: Date.new(1970) },
      { name: 'Nihon Falcom', founded_on: Date.new(1981) },
      { name: 'Ninja Theory', founded_on: Date.new(2000) },
      { name: 'Ninjabee', founded_on: Date.new(2005) },
      { name: 'Nintendo', founded_on: Date.new(1889) },
      { name: 'Nippon Ichi Software', founded_on: Date.new(1991) },
      { name: 'Nokia', founded_on: Date.new(1865) },
      { name: 'Nordeus', founded_on: Date.new(2009) },
      { name: 'Nordic Games GmbH', founded_on: Date.new(2011) },
      { name: 'Nova Games', founded_on: Date.new(2014) },
      { name: 'Novalogic', founded_on: Date.new(1985) },
      { name: 'Novarama', founded_on: Date.new(2003) },
      { name: 'Obsidian Entertainment', founded_on: Date.new(2004) },
      { name: 'Ocean Software', founded_on: Date.new(1984) },
      { name: 'Oddworld Inhabitants', founded_on: Date.new(1994) },
      { name: 'Origin Systems', founded_on: Date.new(1983) },
      { name: 'Outrage Entertainment', founded_on: Date.new(1996) },
      { name: 'Outsmart Studios', founded_on: Date.new(2005) },
      { name: 'Overkill Software', founded_on: Date.new(2009) },
      { name: 'Oxygen Games', founded_on: Date.new(2004) },
      { name: 'Oxygen Studios', founded_on: Date.new(2006) },
      { name: 'Page 44 Studios', founded_on: Date.new(1998) },
      { name: 'Panasonic', founded_on: Date.new(1918,3,13) },
      { name: 'Pandemic Studios', founded_on: Date.new(1998) },
      { name: 'Pangea Software', founded_on: Date.new(1987) },
      { name: 'Panther Games Pty Ltd', founded_on: Date.new(1985) },
      { name: 'Paon', founded_on: Date.new(1999) },
      { name: 'Papaya Studio', founded_on: Date.new(1999) },
      { name: 'Paradox Interactive', founded_on: Date.new(1998) },
      { name: 'Parallax Software', founded_on: Date.new(1993) },
      { name: 'Pax Softnica', founded_on: Date.new(1983) },
      { name: 'Pendulo Studios', founded_on: Date.new(1993) },
      { name: 'Penguin Software', founded_on: Date.new(1978) },
      { name: 'Perfect World', founded_on: Date.new(2004) },
      { name: 'Persha Studia', founded_on: Date.new(2000) },
      { name: 'Petroglyph', founded_on: Date.new(2003) },
      { name: 'Petroglyph Games', founded_on: Date.new(2003) },
      { name: 'Phantagram', founded_on: Date.new(1994) },
      { name: 'Phenomic Game Development', founded_on: Date.new(1997) },
      { name: 'Philips', founded_on: Date.new(1891,5,15) },
      { name: 'Pi Studios', founded_on: Date.new(2002) },
      { name: 'Piranha Bytes', founded_on: Date.new(1997) },
      { name: 'Pivotal Games', founded_on: Date.new(2000) },
      { name: 'Pixel Press', founded_on: Date.new(2013) },
      { name: 'Platinum Games', founded_on: Date.new(2006) },
      { name: 'Playdead', founded_on: Date.new(2006) },
      { name: 'Playdom', founded_on: Date.new(2009) },
      { name: 'PlayFirst', founded_on: Date.new(2004) },
      { name: 'Playfish', founded_on: Date.new(2007) },
      { name: 'Playground Games', founded_on: Date.new(2009) },
      { name: 'Playlogic Entertainment, Inc.', founded_on: Date.new(2002) },
      { name: 'Playmates Toys', founded_on: Date.new(1966) },
      { name: 'Polyphony Digital', founded_on: Date.new(1998) },
      { name: 'PopCap Games', founded_on: Date.new(2000) },
      { name: 'Press Play', founded_on: Date.new(2006) },
      { name: 'Programma International', founded_on: Date.new(1983) },
      { name: 'Psygnosis', founded_on: Date.new(1984) },
      { name: 'Punch Entertainment', founded_on: Date.new(2005) },
      { name: 'Pyro Studios', founded_on: Date.new(1996) },
      { name: 'Q Entertainment', founded_on: Date.new(2003) },
      { name: 'Q-Games', founded_on: Date.new(2001) },
      { name: 'Quantic Dream', founded_on: Date.new(1997) },
      { name: 'R2Games', founded_on: Date.new(2010) },
      { name: 'Radical Entertainment', founded_on: Date.new(1991) },
      { name: 'Rage Software', founded_on: Date.new(1992) },
      { name: 'Rainbow Studios', founded_on: Date.new(1996) },
      { name: 'Rare', founded_on: Date.new(1985) },
      { name: 'Raven Software', founded_on: Date.new(1990) },
      { name: 'Reality Pump Studios', founded_on: Date.new(1995) },
      { name: 'Realtime Associates', founded_on: Date.new(1986) },
      { name: 'Realtime Worlds', founded_on: Date.new(2002) },
      { name: 'Rebellion Developments', founded_on: Date.new(1992) },
      { name: 'Red Storm Entertainment', founded_on: Date.new(1996) },
      { name: 'RedLynx', founded_on: Date.new(2000) },
      { name: 'Redtribe', founded_on: Date.new(2003) },
      { name: 'Reflections Interactive', founded_on: Date.new(1984) },
      { name: 'Reflexive Entertainment', founded_on: Date.new(1997) },
      { name: 'Relic Entertainment', founded_on: Date.new(1997) },
      { name: 'Remedy Entertainment', founded_on: Date.new(1995) },
      { name: 'Respawn Entertainment', founded_on: Date.new(2010) },
      { name: 'Reto-Moto', founded_on: Date.new(2008) },
      { name: 'Retro Studios', founded_on: Date.new(1998) },
      { name: 'Revolution Software', founded_on: Date.new(1990) },
      { name: 'Riot Games', founded_on: Date.new(2006) },
      { name: 'Rising Star Games', founded_on: Date.new(2004) },
      { name: 'Rockstar Games', founded_on: Date.new(1998) },
      { name: 'Rocksteady Studios', founded_on: Date.new(2005) },
      { name: 'Rovio Entertainment', founded_on: Date.new(2003) },
      { name: 'RRI Games Studios, Ltd.', founded_on: Date.new(2012) },
      { name: 'Ruffian Games', founded_on: Date.new(2008) },
      { name: 'Runic Games', founded_on: Date.new(2008) },
      { name: 'Running With Scissors', founded_on: Date.new(1997) },
      { name: 'Sammy Studios', founded_on: Date.new(2004) },
      { name: 'Sand Grain Studios', founded_on: Date.new(2002) },
      { name: 'Sanuk Games', founded_on: Date.new(2003) },
      { name: 'SCE Studio Liverpool', founded_on: Date.new(1984) },
      { name: 'SCi Entertainment', founded_on: Date.new(1988) },
      { name: 'SCS Software', founded_on: Date.new(1997) },
      { name: 'Sega', founded_on: Date.new(1960,3,6) },
      { name: 'Sega Sammy Holdings', founded_on: Date.new(2004) },
      { name: 'Serious Games Interactive', founded_on: Date.new(2005) },
      { name: 'SETA Corporation', founded_on: Date.new(1985) },
      { name: 'Shanda', founded_on: Date.new(1999) },
      { name: 'Shrapnel Games', founded_on: Date.new(1999) },
      { name: 'Sierra Entertainment', founded_on: Date.new(1979) },
      { name: 'Silicon Knights', founded_on: Date.new(1992) },
      { name: 'Silicon Studio', founded_on: Date.new(2000) },
      { name: 'Sledgehammer Games', founded_on: Date.new(2009) },
      { name: 'Slitherine', founded_on: Date.new(2000) },
      { name: 'Snail Games', founded_on: Date.new(2000) },
      { name: 'SNK', founded_on: Date.new(1978) },
      { name: 'Snowblind Studios', founded_on: Date.new(1997) },
      { name: 'Sobee Studios', founded_on: Date.new(2000) },
      { name: 'Software 2000', founded_on: Date.new(1987) },
      { name: 'Sonic Team', founded_on: Date.new(1988) },
      { name: 'Sony', founded_on: Date.new(1946,7,5) },
      { name: 'Sony Computer Entertainment', founded_on: Date.new(1987) },
      { name: 'Sony Pictures Digital', founded_on: Date.new(1997) },
      { name: 'Sora Ltd.', founded_on: Date.new(2005) },
      { name: 'SouthPeak Games', founded_on: Date.new(1996) },
      { name: 'Spectrum HoloByte', founded_on: Date.new(1983) },
      { name: 'Spellbound Entertainment', founded_on: Date.new(1994) },
      { name: 'Spike', founded_on: Date.new(1991) },
      { name: 'Spike Chunsoft', founded_on: Date.new(2012) },
      { name: 'Spil Games', founded_on: Date.new(2001) },
      { name: 'Splash Damage', founded_on: Date.new(2001) },
      { name: 'Sproing Interactive Media', founded_on: Date.new(2001) },
      { name: 'Square', founded_on: Date.new(1983) },
      { name: 'Square Electronic Arts', founded_on: Date.new(1998) },
      { name: 'Square Enix', founded_on: Date.new(2003) },
      { name: 'Stainless Games', founded_on: Date.new(1993) },
      { name: 'Stainless Steel Studios', founded_on: Date.new(1998) },
      { name: 'Star Vault', founded_on: Date.new(2007) },
      { name: 'Starbreeze Studios', founded_on: Date.new(1998) },
      { name: 'Stardock', founded_on: Date.new(1991) },
      { name: 'Sting Entertainment', founded_on: Date.new(1989) },
      { name: 'Strategic Simulations(SSI)', founded_on: Date.new(1979) },
      { name: 'Strategy First', founded_on: Date.new(1988) },
      { name: 'Strawdog Studios', founded_on: Date.new(2003) },
      { name: 'Straylight Studios', founded_on: Date.new(2004) },
      { name: 'Streamline Studios', founded_on: Date.new(2001) },
      { name: 'Streum On Studio', founded_on: Date.new(2007) },
      { name: 'Success', founded_on: Date.new(1978) },
      { name: 'Sucker Punch Productions', founded_on: Date.new(1997) },
      { name: 'Sumo Digital', founded_on: Date.new(2003) },
      { name: 'Sunflowers Interactive Entertainment Software', founded_on: Date.new(1993) },
      { name: 'Sunsoft', founded_on: Date.new(1981) },
      { name: 'Supercell', founded_on: Date.new(2010) },
      { name: 'SuperVillain Studios', founded_on: Date.new(2004) },
      { name: 'Swingin\' Ape Studios', founded_on: Date.new(2000) },
      { name: 'Tag Games', founded_on: Date.new(2006) },
      { name: 'Taito', founded_on: Date.new(1953) },
      { name: 'Takara', founded_on: Date.new(1955) },
      { name: 'Takara Tomy', founded_on: Date.new(2006) },
      { name: 'Take-Two Interactive', founded_on: Date.new(1993) },
      { name: 'TaleWorlds', founded_on: Date.new(2005) },
      { name: 'TalonSoft', founded_on: Date.new(2005) },
      { name: 'Tamsoft', founded_on: Date.new(1992) },
      { name: 'Tango Gameworks', founded_on: Date.new(2010) },
      { name: 'Tantalus Media', founded_on: Date.new(1994) },
      { name: 'Tantrumedia', founded_on: Date.new(2003) },
      { name: 'Tate Interactive', founded_on: Date.new(2002) },
      { name: 'Taxan', founded_on: Date.new(1981) },
      { name: 'Team Bondi', founded_on: Date.new(2003) },
      { name: 'Team17', founded_on: Date.new(1990) },
      { name: 'Techland', founded_on: Date.new(1991) },
      { name: 'Technos Japan', founded_on: Date.new(1981) },
      { name: 'Tecmo', founded_on: Date.new(1967) },
      { name: 'Telltale Games', founded_on: Date.new(2004) },
      { name: 'Tencent', founded_on: Date.new(1998) },
      { name: 'Tequila Works', founded_on: Date.new(2009) },
      { name: 'Terminal Reality', founded_on: Date.new(1994) },
      { name: 'Teyon', founded_on: Date.new(2006) },
      { name: 'The 3DO Company', founded_on: Date.new(1991) },
      { name: 'The Bitmap Brothers', founded_on: Date.new(1987) },
      { name: 'The Chinese Room', founded_on: Date.new(2007) },
      { name: 'The Learning Company', founded_on: Date.new(1980) },
      { name: 'The Workshop Entertainment, Inc.', founded_on: Date.new(2008) },
      { name: 'The9', founded_on: Date.new(1999) },
      { name: 'THQ', founded_on: Date.new(1989) },
      { name: 'Three Rings Design', founded_on: Date.new(2001) },
      { name: 'TimeGate Studios', founded_on: Date.new(1998) },
      { name: 'Tomy', founded_on: Date.new(2006) },
      { name: 'TopWare Interactive', founded_on: Date.new(1995) },
      { name: 'Torpex Games', founded_on: Date.new(2005) },
      { name: 'Torus Games', founded_on: Date.new(1994) },
      { name: 'Tose', founded_on: Date.new(1979) },
      { name: 'Toys for Bob', founded_on: Date.new(1989) },
      { name: 'Tradewest', founded_on: Date.new(1986) },
      { name: 'Transmission Games', founded_on: Date.new(1996) },
      { name: 'Trapdoor', founded_on: Date.new(2010) },
      { name: 'Traveller\'s Tales', founded_on: Date.new(1990) },
      { name: 'Treyarch', founded_on: Date.new(1996) },
      { name: 'Tri-Ace', founded_on: Date.new(1995) },
      { name: 'Tripwire Interactive', founded_on: Date.new(2005) },
      { name: 'Triumph Studios', founded_on: Date.new(1997) },
      { name: 'TT Games', founded_on: Date.new(2005) },
      { name: 'Turn 10 Studios', founded_on: Date.new(2001) },
      { name: 'Turtle Rock Studios', founded_on: Date.new(2002) },
      { name: 'Two Tribes', founded_on: Date.new(2000) },
      { name: 'Tygron', founded_on: Date.new(2005) },
      { name: 'Typhoon Games', founded_on: Date.new(2001) },
      { name: 'U.S. Gold', founded_on: Date.new(1984) },
      { name: 'Ubisoft', founded_on: Date.new(1986) },
      { name: 'Ultimate Play the Game', founded_on: Date.new(1982) },
      { name: 'Ultra Games', founded_on: Date.new(1988) },
      { name: 'Unique Development Studios', founded_on: Date.new(1993) },
      { name: 'United Front Games', founded_on: Date.new(2006) },
      { name: 'Universomo', founded_on: Date.new(2002) },
      { name: 'Valve Corporation', founded_on: Date.new(1996) },
      { name: 'Vanillaware', founded_on: Date.new(2002) },
      { name: 'Venan Entertainment', founded_on: Date.new(2002) },
      { name: 'Vic Tokai', founded_on: Date.new(1977) },
      { name: 'Vicarious Visions', founded_on: Date.new(1990) },
      { name: 'Vigil Games', founded_on: Date.new(2005) },
      { name: 'Virtual Adventures Inc.', founded_on: Date.new(1994) },
      { name: 'Virtual Heroes, Inc.', founded_on: Date.new(2004) },
      { name: 'Visceral Games', founded_on: Date.new(1998) },
      { name: 'Visual Concepts', founded_on: Date.new(1988) },
      { name: 'Vivendi Games', founded_on: Date.new(1993) },
      { name: 'Viwawa', founded_on: Date.new(2007) },
      { name: 'Volition, Inc.', founded_on: Date.new(1996) },
      { name: 'Vostok Games', founded_on: Date.new(2012) },
      { name: 'VoxelStorm', founded_on: Date.new(2012) },
      { name: 'Wahoo Studios', founded_on: Date.new(2001) },
      { name: 'Wanako Games', founded_on: Date.new(2002) },
      { name: 'Wargaming', founded_on: Date.new(1998) },
      { name: 'Wargaming Saint Petersburg', founded_on: Date.new(1991) },
      { name: 'Wargaming.net', founded_on: Date.new(1998) },
      { name: 'Warhorse Studios', founded_on: Date.new(2011) },
      { name: 'Warner Bros. Interactive', founded_on: Date.new(1993) },
      { name: 'WayForward Technologies', founded_on: Date.new(1990) },
      { name: 'WB Games', founded_on: Date.new(1988) },
      { name: 'Webfoot Technologies', founded_on: Date.new(1993) },
      { name: 'Webzen', founded_on: Date.new(2000) },
      { name: 'Wideload Games', founded_on: Date.new(2003) },
      { name: 'Wildfire Studios', founded_on: Date.new(1995) },
      { name: 'Wisdom Tree', founded_on: Date.new(1989) },
      { name: 'Wolfire Games', founded_on: Date.new(2003) },
      { name: 'Working Designs', founded_on: Date.new(1986) },
      { name: 'World Forge', founded_on: Date.new(2004) },
      { name: 'XPEC Entertainment', founded_on: Date.new(2000) },
      { name: 'XSEED Games', founded_on: Date.new(2005) },
      { name: 'Yager Development', founded_on: Date.new(1999) },
      { name: 'Yuisy', founded_on: Date.new(2010) },
      { name: 'Yuke\'s', founded_on: Date.new(1993) },
      { name: 'YY Incorporation', founded_on: Date.new(2004) },
      { name: 'ZeniMax Media', founded_on: Date.new(1999) },
      { name: 'ZeniMax Online Studios', founded_on: Date.new(2007) },
      { name: 'Zipper Interactive', founded_on: Date.new(1995) },
      { name: 'Zombie Studios', founded_on: Date.new(1994) },
      { name: 'ZootFly', founded_on: Date.new(2002) },
      { name: 'Zushi Games', founded_on: Date.new(1999) },
      { name: 'Zuxxez Entertainment', founded_on: Date.new(2001) },
      { name: 'Zylom', founded_on: Date.new(2001) },
      { name: 'Zynga', founded_on: Date.new(2007) }
    ].each do |company|
      Company.find_or_create_by(
        name: company[:name],
        founded_on: company[:founded_on]
      )
    end
  end
end