module Seeds
  def self.seed_genres
    [
      'Action',
      'Platform',
      'Shooter',
      'Adventure',
      'Text Adventure',
      'Point-and-Click Adventure',
      'Action-Adventure',
      'Stealth',
      'Survival Horror',
      'Metroidvania',
      'Role-playing',
      'Action RPG',
      'Roguelike',
      'Tactical RPG',
      'Sandbox RPG',
      'Simulation',
      'Construction and Management Simulation',
      'Life Simulation',
      'Vehicle Simulation',
      'Strategy',
      '4X',
      'Real-time Strategy',
      'Tower Defense',
      'Turn-based Strategy',
      'Wargame',
      'Sports',
      'Soccer',
      'Football',
      'Basketball',
      'Boxing',
      'Tennis',
      'Puzzle',
      'Bowling',
      'Billiards',
      'Board Game',
      'Volleyball',
      'Ice Hockey',
      'Golf',
      'Skateboarding',
      'Fishing',
      'Wrestling',
      'Baseball',
      'Pinball',
      'Cricket',
      'Card',
      'Beat \'em up',
      'Racing',
      'Fighting',
      'Trivia',
      'Music',
      'Party',
      'Casual',
      'Massively Multiplayer Online'
    ].each { |genre_name| Genre.find_or_create_by(name: genre_name) }
  end
end
