default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['retroraider_db_user'] %>
  password: <%= ENV['retroraider_db_pass'] %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: retroraider_development

test:
  <<: *default
  database: retroraider_testing

production:
  <<: *default
  database: retroraider_production
